[package]
name = "minigrep"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex="1.7.0"

[profile.release]
opt-level= 3
debug = false
